apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: open-local-lvm
provisioner: local.csi.aliyun.com
parameters:
  volumeType: "LVM"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true