apiVersion: v1
kind: Node
metadata:
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: master-3
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  name: master-3
status:
  capacity:
    cpu: "8"
    ephemeral-storage: 61255492Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 16Gi
    pods: "110"
  allocatable:
    cpu: "4"
    ephemeral-storage: 61255492Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 1Gi
    pods: "110"